### ISSUE TITLE
Incorrect column tuple length when using PostgreSQL

### ISSUE THREAD

**Issue by th31nitiate** [choptastic/sql_bridge#10]
I don't know if this is an issue for anyone else. It seems that with PostgreSQL there seems to be errors when using SQL bridge on version `0.6.1`.  The main issues seems to be the length of the tuple in the columns returned from PostgreSQL. I am not sure if this is due to the version of PostgreSQL. I managed to fix the issue and currently working out of `_checkouts`.

I believe the version of `epgsql` should be the same. I'm not sure if anyone else has experienced this. I have checked the commits to master and non seem to cater to this issue. I was wondering if anyone else is experiencing this.

```
diff --git a/src/sql_bridge_epgsql.erl b/src/sql_bridge_epgsql.erl
index 8be75ce..2e2b28b 100644
--- a/src/sql_bridge_epgsql.erl
+++ b/src/sql_bridge_epgsql.erl
@@ -130,7 +130,7 @@ format_result_inner(map, {ok, Columns, Rows}) ->
        format_maps(Columns, Rows).
 
 columns_to_coltypes(Columns) ->
-    [{list_to_atom(binary_to_list(Col)), Type} || {column, Col, Type, _, _, _} <- Columns].
+    [{binary_to_atom(Col), Type} || {column, Col, Type, _, _, _, _, _, _} <- Columns].

```

**Comment by choptastic** [comment]
Hi @th31nitiate! Oh no! I'll have to check this out.  I'll admit it has been a while since I've used this with PGsql (I'm mostly on mariadb), so I'll check this out.

Your fix certainly does look legit, so I'm sure something like a record definition changed in epgsql since I worked on it.

I definitely need to set up some automated tests for this to ensure things aren't breaking.

Thanks!

**Comment by th31nitiate** [comment]
Hmmm I could help stub out some tests but not so sure about how automated we can make them. 

I see here that there is already tests but their not automated in an CI pipeline per say. The only issue I seem to see is how to represent the data from the database or the database for that matter.

GitHub offers 2000 CI/CD minutes per month. I can look at adding those tests if you want ? I can do the CI process as well and maybe the CD if you consider reviewing the PR ?

I can start off in my branch verify everything then request to merge the PR.

**Comment by choptastic** [comment]
Thanks for the reminder about the GH actions.

I did some working through the test cases, since honestly, I haven't run them in a long time, and man, they were pretty busted.

I've loaded in a variation of your suggestion here: https://github.com/choptastic/sql_bridge/commit/f7f3ebdf54be870620eedf8e041911801302fa35

But I'm also trying to work to get some of the [my changes from my fork](https://github.com/epgsql/epgsql/compare/master...choptastic:epgsql:master) of epgsql brought upstream so that sql_bridge doesn't rely on me maintaining a separate fork.

**Comment by th31nitiate** [comment]
> For local testing purposes and for the sake of improving the simplicity of doing tests locally, I've added a few entries to the `Makefile`
> 
>     * `make dev` (to clone mysql-otp and epgsql into _checkouts)
> 
>     * `make test` - will try to do the necessary setup for pg and mysql, then run the unit tests on them (this was written assuming a standard ubuntu setup).
> 
> 
> So that can help with getting the github CI stuff running, if you did want to work on that configuration (its obviously not going to pass right out of the gate, since a bunch of the tests are failing right now)

Cool, I think for SQL_bridge for the most part its fine since most people running it in production are likely using earlier version of PostgreSQL.

I'm still looking over the test's but there seems to be a few. The most important thing is to ideally ensure tests for the top level functions exist.

I recently noticed that I'm having issues with the  tokenization for variable substitutions when creating queries. It's pretty insane I have had to use `io_lib:format` then pass it to `db:q`.

Thank you for updating that I appreciate it. I'm going to be looking at getting the GitHub actions configured. I will let you know as soon as I have some progress on that.

**Comment by th31nitiate** [comment]
I apologize if your inbox is getting bombarded by failed build notifications. I'm still getting to grips with GitHub actions. Thus there is more than a few failed builds and cant find a way to silence them. 

On the plus side I have made some progress in getting the database provisioned in order to run the test. Though I have run into a few issue of which I was hoping you could help provide some guidance regarding.

I have tried to make the tests to be adaptable to most environments as I am sure not everyone is using GitHub actions. Though when run some of the tests seem to be failing. This is simply due mainly typing errors. I am not sure if to consider them issues or not.

I have 5 failing tests for `PostgreSQL`:

- `sql_bridge_test:main_tests/1:214`:  returning the datetime as binary string while comparing it against string
-  `sql_bridge_test:main_tests/1:213`:  returning the time as binary string while comparing it against string
- `sql_bridge_test:main_tests/1:212`: returning the date as binary string while comparing it against string
- `sql_bridge_test:main_tests/1:210`: returning a float as a string while comparing it against string
- `sql_bridge_test:main_tests/1:164`: fields are not in the correct order. Can be easily resolved by change the way the fields are ordered in create table query.

I have a few tests failing on `mysql`:

- `sql_bridge_test:trans_tests/1:79`: Not too sure whats happening with the Pid look ups
- `sql_bridge_test:trans_tests/1:87`: Not too sure whats happening with the Pid look ups
- `sql_bridge_test:trans_tests/1:88`: Not too sure whats happening with the Pid look ups and rollback
- `sql_bridge_test:trans_tests/1:88`: Not too sure whats happening with the Pid look ups and rollback
- `sql_bridge_test:trans_tests/1:94`: Not entirely sure what this function does


On the online version I seem to get around 17 failures. It mainly regarding the PidLookups so I am going to investigate that a little. 

Though the for most part it seems to be OK.

**Comment by choptastic** [comment]
I haven't been getting bombarded by anything, so that's good :)

As for the failed tests, that's part of what I'm working on - backporting my epgsql changes to mainline.  My version (in choptastic/epgsql) is several hundred commits behind mainline, but my version also has functionality to handle date strings coming in, hence some of the type errors.

Similarly, there are issues coming in with mysql transactions, so I have to investigate that as well.

**Comment by choptastic** [comment]
Oh sweet, the newer versions of epgsql allow custom codecs.  I'm working on those, and that should resolve the epgsql type issues.

**Comment by th31nitiate** [comment]
Well... I guess I will just focus on getting the CI running with test's and also see if there can be any useful features. Though it is highly unlikely that the tests will be passing. Even when I use the modified version I get the following error:
```
Finished in 11.444 seconds
146 tests, 10 failures, 2 cancelled
===> Error running tests
```
Though they seem like very simple issues that can be resolved. If the intention is to get the tests passing. Though a better intention is to have functional code. Nothing that should cause any major issues in my view point.

`db:table_fields(fruit)` is in alphabetical order. It not a bad thing but not a great thing for the tests view point.

When it comes to `epgsql` I would say why not have `sql_bridge` be dependent on your version of it. All that has to be done is to ensure to merge the upstream changes into your version as and when you see fit. You could schedule time for it a few times a year. It should not take more 3 hours of which you can do 3 times a year.  That is about 9 hours out of the whole year.

Regarding the issues associated with some of the transactions. This is something I'm taking the chance to learn more about now. It seems the transaction are created recursively with the following: `erlang:spawn(fun lookup_loop/0)`

I'm going to be looking at the code that defines the tests for a while just to better understand of `eunit` and what's happening here.

**Comment by choptastic** [comment]
Alrighty, I have all the tests for epgsql passing.

This should be much more resilient, and it uses the new codec system, which really simplifies things.

All I had to do with the field names was to return them using the `ordinal_position` defined in the `information_schema` and that resolved it :)

**Comment by choptastic** [comment]
Oh, and as for why I don't want to maintain a fork, there are a few key reasons:

1) Users can have the benefit of using the most up-to-date epgsql and mysql drivers from the real maintainers, which can ensure security patches are addressed more quickly,
2) Practically speaking, I know I won't be good about pulling upstream changes - I'm juggling too many things to take on something like that unless absolutely necessary, and
3) In order for this to be compatible with hex, I would then have to also create a separate (mostly redundant) hex project to maintain and publish. 

But epgsql's new codec system made it convenient for me to front-load my changes (since my changes weren't really protocol-level changes, just formatting changes).  As a result, if epgsql does change something about those codecs, those few changes now exist locally in sql_bridge, and those can be pretty easily updated without having to have fixes like that merged into mainline epgsql.

**Comment by th31nitiate** [comment]
Cool, errrmmm as for the CI stuff its pretty muich done. It's just one stage nothing major. Though it can always be improved based on a workflow you like utilize. 

Here is the branch, let me know if there is anything you would like me to change or try out: https://github.com/th31nitiate/sql_bridge/tree/test-github-actions

Here is an example of the latest action triggered: https://github.com/th31nitiate/sql_bridge/actions/runs/6099962786

There various things we can change. At present it runs on push so each push it will run tests. I change a few things which I detailed in the commit description.

We can make a lot more dynamic but you would have to provide some insights regarding what would be most useful. If you want tests to run only for pull request or when a tag matching a specific regex is triggered. It also possible to exclude branches or even make the tests run separately for via eunit for mysql and postgres.

**Comment by choptastic** [comment]
Looks great! Thanks! Yeah, please go ahead and submit the PR.  I'll merge and resolve conflicts.

Probably the only actual change I'd want to make is to allow the tests to be run locally, rather than exclusively remotely (with the `hostname` being set to `postgres` and `mysql`, I'd want to add something there to so that if not being run as a github action, it just uses the local installation.

If you're down with adding that, sweet. If not, I'm comfortable tinkering with it.

Thanks again for all your help here!

**Comment by th31nitiate** [comment]
I guess those a logical points regarding not having to maintain your own version of `epgsql`. Though if you comfortable with codecs and getting up to speed with it then I guess it would be a much better approach. I just think sometimes if it takes more than like few months to get changes reviewed then it might not the best option. Reducing toil i.e maintenance burden should always be priority.

Regarding those changes I have managed to implement a simple method that involves have to source file locally. You can then change that the variables in the source file. The source them in to the environment. Once done it is possible to run `make test` using the specific config.

The only thing would be hoping that the run is somewhat idempotent. I managed to alter the queries a but basically each time you run `make test` you may get some issues. Though it should not be anything major as you can always alter the sql files locally.

**Comment by choptastic** [comment]
Awesome. Thanks. I'm going to close this particular issue, as the original task has been solved, and future discussion on your CI can be discussed on your PR. Thanks!
